---
device_type: "nxos"
command_list:
  - file_suffix: "inv"
    command: "show inventory"
  - file_suffix: "lic"
    command: "show license"
  - file_suffix: "ver"
    command: "show version"
  - file_suffix: "nos"
    command: "show install active"
...
