---
# Log in and run the commands specified in the group_vars/ files.
- name: "ASA >> Gather Cisco ASA information"
  asa_command:
    commands: "{{ item.command }}"
  register: "CLI_OUTPUT"
  loop: "{{ command_list }}"
  loop_control:
    label: "{{ item.command }}"
...
