---
# Log in and run the commands specified in the group_vars/ files.
- name: "IOSXR >> Gather Cisco IOS-XR information"
  iosxr_command:
    commands: "{{ item.command }}"
  register: "CLI_OUTPUT"
  loop: "{{ command_list }}"
  loop_control:
    label: "{{ item.command }}"
...
